### PR TITLE
fix typo && fix pip install

### PR DESCRIPTION
**Pull request by 6aKa**
remove trailing spaces

### CODE REVIEW

**Comment by MusicDin** [comment]
Hi.

Thanks for your contribution.

I tried setting up cluster using your changes, but I didn't succeed, because `source` command is not found.
It may be due to `/bin/sh` pointing to `/bin/dash` instead of `/bin/bash`. 

So if you could provide some installation instructions for required executable or provide some generic solutions for this problem?

**Comment by 6aKa** [comment]
https://virtualenv.pypa.io/en/legacy/userguide.html

`
For some shells (e.g. the original Bourne Shell) you may need to use the . command, when source does not exist. There are also separate activate files for some other shells, like csh and fish. bin/activate should work for bash/zsh/dash.
`

so need change `source venv/bin/activate` to `. venv/bin/activate`

**Comment by MusicDin** [comment]
Should virtualenv name`venv` be changeable by user? 

As I understand this is *virtualenv project name* where local dependencies will be saved, so maybe someone has already used that name for other projects. So in this case I can make it as a variable in `terraform.tfvars`. 

Or is that name applied only in certain folder and won't interfere with other project with the same name in different directory? In that case I will leave it as it is.

**Comment by 6aKa** [comment]
> Should virtualenv name`venv` be changeable by user?

maybe, but i don't this so. this is temporary local folder for ansible playbook

> As I understand this is _virtualenv project name_ where local dependencies will be saved, so maybe someone has already used that name for other projects. So in this case I can make it as a variable in `terraform.tfvars`.

virtualenv create _virtualenv project name_ folder in current directory, not globally. so you can use one name for _virtualenv project name_ multiple times.
 
> Or is that name applied only in certain folder and won't interfere with other project with the same name in different directory? In that case I will leave it as it is.

for example use two ansible playbooks with python deps 
i see two ways.
1. for all projects in ansible directory if need python deps create own venv with deps.
```
cd ansible/kubespay && virtualenv venv && source venv/bin/activate
pip install -r requirements.txt
_run kubespray playbook_
deactivate

cd ansible/haproxy && virtualenv venv && source venv/bin/activate
pip install -r requirements.txt
_run haproxy playbook_
deactivate
```

2. create globally for example in ansible/venv
```
cd ansible/ && virtualenv venv && source venv/bin/activate
pip install -r kubespay/equirements.txt
_run kubespray playbook_
pip install -r haproxy/requirements.txt
_run haproxy playbook_
deactivate
```

**Comment by MusicDin** [comment]
Thanks for your input. 👍 

I merger your pull request and changed `source` command into `.`.

**Pull request merged**
