### PR TITLE
known_hosts update

### PR DESCRIPTION
**Pull request by 6aKa**
`sed -i` - edit files in place

when vm created, `ssh-keygen && ssh-keyscan` used for update item in known_hosts
when remove_worker clean item with `sed`

please add cleaning when `terraform destroy`, because now clean only worker items

### CODE REVIEW

**Comment by MusicDin** [comment]
Hi,

thanks again for your contribution. I 'm quite busy right now, but I will check everying lately this week.

It's cleaning only worker nodes, because script is intended to scale only worker nodes, so when nodes are being reduced it removes them from `hosts.ini` file. 

When whole cluster is being removed, everything is deleted so `hosts.ini` file doesn't even matter.

**Comment by MusicDin** [comment]
Hi again,

I'm sorry, but I totally misunderstood your pull request a few days ago. 

This is a great addition to the script and I'm going to test this pull request and accept it lately today or maybe tomorrow. 

Thanks for your contribution.

**Comment by MusicDin** [comment]
Hi, 

just to let you know, that now modifications to `~/.ssh/known_hosts` are stable.

Feature can also be disabled in `terraform.tfvars` under `vm_ssh_known_hosts` variable. (Note: boolean **must** be wrapped as string, otherwise it won't work).

**Comment by 6aKa** [comment]
Hi. I'm not good in terraform, that's why I make simple fixes for describe main idea.

**Comment by MusicDin** [comment]
No problem, I really appreciate your help. Thanks.

**Pull request merged**
